### ISSUE TITLE
yolov5 does not use GPU for accelerated prediction 

### ISSUE THREAD

**Issue by quocnhat** [triple-Mu/ncnn-examples#5]
Hi, thanks for your excellent job.
I've successfully built ncnn vulkan and run your project correctly, But I noticed that the GPU is not being used when I set: yolov5.opt.use_vulkan_compute=true
The speed is the same for setting that flag.
any ideas? thank you

**Comment by triple-mu** [comment]
> Hi, thanks for your excellent job. I've successfully built ncnn vulkan and run your project correctly, But I noticed that the GPU is not being used when I set: yolov5.opt.use_vulkan_compute=true The speed is the same for setting that flag. any ideas? thank you

Have you compiled the gpu version of ncnn?

**Comment by quocnhat** [comment]
Sorry, it is solved when I re-install the ncnn Vulkan lib. Thank you for your quick support
